doc:
  repo: https://github.com/OI-Wiki/OI-Wiki
  ref: master

migrator:
  repo: https://github.com/diauweb/oiwiki-migrator
  ref: master

jamstack:
  repo: https://github.com/OI-Wiki/gatsby-oi-wiki
  submodule: gatsby-oi-wiki
  ref: master

