name: Build LaTeX document

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: OI-wiki/OI-Wiki-export
      - name: Build the LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          latexmk_use_xelatex: true
          latexmk_shell_escape: true
          extra_system_packages: |
            unzip
            wget
            curl
            coreutils
            nodejs
            npm
            imagemagick
            libwebp
            librsvg
            git
            py3-pygments
          pre_compile: |
            wget -q "https://github.com/stipub/stixfonts/raw/73d7c426993abacea44288aded4e81b568d57ed1/zipfiles/STIXv2.0.2.zip" -O stix.zip
            unzip -q stix.zip
            wget -q "https://github.com/adobe-fonts/source-han-super-otc/releases/download/20190603/SourceHan.ttc"
            git clone https://github.com/alif-type/xits
            cp xits/*.otf /usr/share/fonts
            git clone https://github.com/dolbydu/font.git
            cp font/unicode/* /usr/share/fonts
            wget -q "http://mirrors.ctan.org/fonts/cm-unicode.zip"
            unzip ./cm-unicode.zip
            cp cm-unicode/fonts/otf/* /usr/share/fonts
            cp STIXv2.0.2/OTF/* /usr/share/fonts
            cp *.ttc /usr/share/fonts
            fc-cache
            cd oi-wiki-export
            npm i
            git clone https://github.com/OI-wiki/OI-wiki.git
            node index.js ./OI-wiki
          root_file: |
            oi-wiki-export.tex
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: Exported PDF
          path: ./oi-wiki-export/oi-wiki-export.pdf
          retention-days: 7
