  
name: GitHub Pages

on:
  push:
    branches:
      - master
  workflow_dispatch:
      inputs:
        doc_checkout_from_repo:
          description: The document repository to checkout from.
          required: false
          default: 'OI-Wiki/OI-Wiki'
        doc_checkout_from_ref:
          description: The document repository ref to checkout from.
          required: false
          default: 'master'
        make_destination:
          description: Whether to create repo if not exist
          required: false
          default: "false"
        destination:
          description: GitHub Pages repository to deploy to
          required: false
          default: "OI-Wiki/oiwiki-bootstarp"
jobs:
  deploy:
    # env:
    #  PRODUCTION: true
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.17.x'

      - name: Get node version
        id: node-version
        run: |
          echo "::set-output name=ver::$(node --version)"
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Dependencies
        run: |
          sudo apt install python3-setuptools 
          pip3 install -r requirements.txt

      - name: Build
        run: | 
          python3 build.py
          rm ./public/CNAME
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./public
          force_orphan: true
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          cname: wiki.akioi.icu