name: GitHub Pages

on:
  push:
    branches:
      - master
  workflow_call:
  workflow_dispatch:
    inputs:
      doc_repo:
        description: Document repository
        required: false
        default: "OI-Wiki/OI-Wiki"
      doc_ref:
        description: Document repository ref
        required: false
        default: "master"
      jamstack_repo:
        description: Jamstack repository
        required: false
        default: "OI-Wiki/gatsby-oi-wiki"
      jamstack_ref:
        description: Jamstack repository ref
        required: false
        default: "master"
      migrator_repo:
        description: Migrator repository
        required: false
        default: "OI-Wiki/oiwiki-migrator"
      migrator_ref:
        description: Migrator repository ref
        required: false
        default: "master"

jobs:
  deploy:
    env:
     PRODUCTION: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"
      
      - name: Install Dependencies
        run: |
          sudo apt install python3-setuptools 
          pip3 install -r requirements.txt
      - name: Reconfigure
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: >
          yq e -i '
              .doc.repo = "https://github.com/${{ github.event.inputs.doc_repo }}"
            | .doc.ref = "${{ github.event.inputs.doc_ref }}"
            | .jamstack.repo = "https://github.com/${{ github.event.inputs.jamstack_repo }}"
            | .jamstack.ref = "${{ github.event.inputs.jamstack_ref }}"
            | .migrator.repo = "https://github.com/${{ github.event.inputs.migrator_repo }}"
            | .migrator.ref = "${{ github.event.inputs.migrator_ref }}"
          ' config.yml
      - name: Build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python3 build.py
          rm ./public/CNAME

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          force_orphan: true
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
          cname: next.oi-wiki.org
